title: JUST_the_DOCS_Paula
description: JUST_the-_DOCS_Paula
theme: just-the-docs

url: https://Baniolka/JUST_the-_DOCS_Paula.io

aux_links:
  Template Repository: https://github.com/Baniolka/JUST_the-_DOCS_Paula
