title: JUST_the_DOCS_Paula
description: JUST_the-_DOCS_Paula
theme: just-the-docs

url: https://Baniolka/JUST_the-_DOCS_Paula.io
nav_external_links_new_tab: true
aux_links:
  Template Repository: https://github.com/Baniolka/JUST_the-_DOCS_Paula
